name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"   
  workflow_dispatch:        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@master
        id: top-langs
        with:
          username: maiih
          theme: dracula
          layout: compact
          card_width: 400

      - name: Save SVG
        run: |
          mkdir -p output
          echo '${{ steps.top-langs.outputs.svg }}' > output/top-langs.svg

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/top-langs.svg
          git commit -m "Update stats" || echo "No changes to commit"
          git push
